
import { useEffect } from "react";

/*all css import*/
import "../../styles/main.css";
import {Helmet} from "react-helmet";

function MyApp({ Component, pageProps }) {
  useEffect(() => {
    import("../../public/assets/js/bootstrap.bundle.min.js");
  });
  return (
    <>
      <Helmet>
          <title>Scooby - Petcare & Pet Shop NextJs Template</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="assets/images/sm-logo.svg" />
      </Helmet>
        <Component {...pageProps} />
    </>
  );
}

export default MyApp;
